# For more ideas from Vim, see https://github.com/LGUG2Z/helix-vim/blob/59b56365f0d54dba15026b4c51969b5fd4da5c98/config.toml

[editor]
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
"%" = "match_brackets"
V = ["select_mode", "extend_to_line_bounds"]
C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]
Z = { Z = [":write-quit"] }
p = ["paste_clipboard_after", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]
"*" = ["select_mode", "extend_next_word_start", "normal_mode", "search_selection", "search_next"]

[keys.normal.y]
y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.select]
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
"%" = "match_brackets"
y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
Z = { Z = [":write-quit"] }
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
